### ISSUE TITLE
Investigate spot price returned in the quotes

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/sqs#106]
![image](https://github.com/osmosis-labs/sqs/assets/34196718/c90ced3d-1dcc-447d-bbe1-a5f936261782)

**Comment by jonator** [comment]
Also IMO it'd be a bit cleaner to return the amount as the out token's base amount, instead of w decimals included, as done with all other amounts.

**Comment by p0mvn** [comment]
OK

**Comment by p0mvn** [comment]
Keeping open till deployed

**Comment by p0mvn** [comment]
Deployed
