### ISSUE TITLE
when humandenoms=true, map the microdenom also

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/sqs#164]
Microdenoms are used all over the back end, so when we have humandenom set to true, let's also apply the same sugar to requests for microdenoms

Eg, let's make this work:

curl -X 'GET' \ 'https://sqsprod.osmosis.zone/router/quote?tokenIn=10000akt&tokenOutDenom=usdc&humanDenoms=true' \ -H 'accept: application/json'

and also

curl -X 'GET' \ 'https://sqsprod.osmosis.zone/router/quote?tokenIn=10000uakt&tokenOutDenom=usdc&humanDenoms=true' \ -H 'accept: application/json'

**Comment by p0mvn** [comment]
Thanks for the issue

`humanDenoms` is a flag to indicate that the provided tokens are in human format rather than IBC/chain. If IBC/chain denoms are provided, `humanDenoms` should be false or not present in the query.

Does explanation above address this request?
