### ISSUE TITLE
[TechDebt] Remove any references and tooling around Redis

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/sqs#240]
We don't use Redis anymore but there is a lot of unused tech debt remaining

- Remove any Redis references
- Update any necessary configs
- Update `infrastrcture` repo configs to remove Redis stuff

**Comment by deividaspetraitis** [comment]
Hey @p0mvn, I would be happy to help with this task if it's still relevant! I have quickly skimmed over the source source and have noticed that mostly that's docs, and `Makefile` is that right?

**Comment by p0mvn** [comment]
That sounds right! I would appreciate help on this. Thank you!
