### ISSUE TITLE
[TechDebt] Review and remove unused configs

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/sqs#243]
There are a number of configs that have become obsolete but are still present, causing us overhead.

An example:

```
enable-overwrite-routes-cache
```

## DoD

* Review and remove unused configs
* `infrastructure` repository updated
* `sqs` updated
* manual stage deployment CI passes post-update

**Comment by deividaspetraitis** [comment]
hey @p0mvn, I would be happy to take this one if you think it's still revelant!

**Comment by p0mvn** [comment]
@deividaspetraitis yes, please.

Let me know if you have questions about these configs. I suggest following references to see what is used vs what isn't.

**Comment by deividaspetraitis** [comment]
Hey @p0mvn, I see that this task is still opened, I was wondering do you think there is still something left to be done? Let me know if I can help you with that in such case.

**Comment by p0mvn** [comment]
Hey @deividaspetraitis thanks for following up.

I'm keeping this open since we need to update the configs in private infra repositories. I will tackle that and close, once complete.

There is nothing outstanding code-wise though. Thanks again for getting this in
