### ISSUE TITLE
Reintroduce flight records

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/sqs#254]
Docker build fails withour a clear reason:
https://github.com/osmosis-labs/sqs/actions/runs/9238009470/job/25415613139

As a result, this PR was reverted: https://github.com/osmosis-labs/sqs/pull/253

The regular build passes for the same change.

The suspicion is that the problem is with the Docker build process but needs to be investigated more

**Comment by p0mvn** [comment]
We will also need to add these configs to the `infrastructure repo`

**Comment by deividaspetraitis** [comment]
hey @p0mvn, I am happy give try on this if that's still relevant, but please suggest in case there is something having higher importance. I think I would need help adding configs to the `infrastructure repo` afterwards.

**Comment by p0mvn** [comment]
Yes, please. I would appreciate help on this.

I can help with making the necessary changes to the private infrastructure repo.

To validate that this builds, we would need to run 'make build-reproducible'

**Comment by deividaspetraitis** [comment]
Got it, thanks! Then I am on it and will open PR once it's ready.

**Comment by p0mvn** [comment]
@deividaspetraitis could you please check your email? I've reached out to connect

**Comment by deividaspetraitis** [comment]
@p0mvn thanks for pinging me here as well! I have just replied a few minutes ago.
