### ISSUE TITLE
[Q3] Auto-update asset list at regular intervals

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/sqs#279]
Currently, we need to redeploy SQS nodes to get SQS updates.

## DoD

* Mechanism to update asset list without redeployment
* Fault tolerance around new list being broken and falling back
* Observability
* Unit tests

**Comment by p0mvn** [comment]
More context:

Let's have a config to enable this feature so that we can turn it on if something is breaking.

I suggest having a config value under [grpc-ingester](https://github.com/osmosis-labs/sqs/blob/3ddc4a6f46c4c8b59919d34158b5208253633aef/config.json#L49) named `asset-list-update-height-interval`.

If the value is non-zero, it would represent the frequency at which we refetch the asset list in terms of heights. For example, if interval is 1, means every height. If 5, every 5 height - 0, 5, 10 and so on.

It should be as simple as adding a call to a separate goroutine to refetch and update the asset list somewhere [here](https://github.com/osmosis-labs/sqs/blob/3ddc4a6f46c4c8b59919d34158b5208253633aef/ingest/usecase/ingest_usecase.go#L101) based on config.

**Comment by deividaspetraitis** [comment]
Hey @p0mvn I am happy to pick this up. Thanks for providing some context and guidance!

**Comment by deividaspetraitis** [comment]
This feature was delivered under [PR-375](https://github.com/osmosis-labs/sqs/pull/375), marking this task as completed.
