### ISSUE TITLE
Add humanDenoms support to `/custom-direct-quote`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/sqs#324]
Do you mind please adding humanDenoms support? Please see `/router/quote` for reference

_Originally posted by @p0mvn in https://github.com/osmosis-labs/sqs/pull/284#discussion_r1640221467_

**Comment by p0mvn** [comment]
@deividaspetraitis ref: https://github.com/osmosis-labs/sqs/pull/284#pullrequestreview-2119062224

Do you have capacity to help with this please 🙏 ?

**Comment by deividaspetraitis** [comment]
It's second on my list then! :muscle:

**Comment by deividaspetraitis** [comment]
Human denoms support was added under [PR-420](https://github.com/osmosis-labs/sqs/pull/420), closing this task as completed.
