### ISSUE TITLE
Cover /router/custom-direct-quote with integration tests

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/sqs#325]
We should cover this endpoint by our new integration test suite.

Please see reference here (similar to `/router/quote`:
https://github.com/osmosis-labs/sqs/blob/d63e8c937378c68704976de86cf2d59cdfd6a0e0/tests/test_router_quote.py#L31

Please see this for set up:
https://github.com/osmosis-labs/sqs/blob/d63e8c937378c68704976de86cf2d59cdfd6a0e0/Makefile#L190-L202

_Originally posted by @p0mvn in https://github.com/osmosis-labs/sqs/pull/284#discussion_r1640230378_

**Comment by p0mvn** [comment]
@deividaspetraitis ref: https://github.com/osmosis-labs/sqs/pull/284#pullrequestreview-2119062224

Do you have capacity to help with this please 🙏 ?

**Comment by deividaspetraitis** [comment]
Let's do this, I am on it! :rocket:

**Comment by deividaspetraitis** [comment]
Tests were added under [PR-420](https://github.com/osmosis-labs/sqs/pull/420), closing this task.
