### ISSUE TITLE
`Int64() out of bound` for estimating quote on asset with large decimal

### ISSUE THREAD

**Issue by y-pakorn** [osmosis-labs/sqs#431]
When estimating quote using `in_denom` as a asset with large decimal, for example, `axlETH` to `allETH`. The router would return `error when calculating out by in in route: Int64() out of bound` or `error when calculating out by in in route: Int64() out of bound, tokenOutDenom (factory/osmo1k6c8jln7ejuqwtqmay3yvzrg3kueaczl96pk067ldg8u835w0yhsw27twm/alloyed/allETH)` as error message when quoting with amount > 10 ETH

Affected endpoints: `router/quote`, `router/custom_direct_quote`

Example query: [https://sqs.osmosis.zone/router/quote?tokenIn=10000000000000000000ibc%2F64E62451C9A5682FF3047429C6E4714A02CDC0C35DE35CAB01E18D1188004CEB&tokenOutDenom=factory%2Fosmo1k6c8jln7ejuqwtqmay3yvzrg3kueaczl96pk067ldg8u835w0yhsw27twm%2Falloyed%2FallETH&poolID=1878](https://sqs.osmosis.zone/router/quote?tokenIn=10000000000000000000ibc%2F64E62451C9A5682FF3047429C6E4714A02CDC0C35DE35CAB01E18D1188004CEB&tokenOutDenom=factory%2Fosmo1k6c8jln7ejuqwtqmay3yvzrg3kueaczl96pk067ldg8u835w0yhsw27twm%2Falloyed%2FallETH&poolID=1878)

**Comment by p0mvn** [comment]
Thanks for reporting. Fix merged:
[https://github.com/osmosis-labs/sqs/commit/296529eaafcf88683d473abe37bba7496d2cc614](https://github.com/osmosis-labs/sqs/commit/296529eaafcf88683d473abe37bba7496d2cc614)

**Comment by y-pakorn** [comment]
Thank you! that was fast lol
