### ISSUE TITLE
Routing Issue for Token ibc/4925733868E7999F5822C961ADE9470A7FC5FA4A560BAE1DE102783C3F64C201 on Osmosis Network

### ISSUE THREAD

**Issue by raphaellafar** [osmosis-labs/sqs#539]
The token `ibc/4925733868E7999F5822C961ADE9470A7FC5FA4A560BAE1DE102783C3F64C201` is currently facing routing issues on the Osmosis network. Users are reporting difficulties in trading and using this token on decentralized exchanges, which significantly impacts its liquidity and availability within the ecosystem.

The expected functionality would allow unrestricted routing for this token, making it available for seamless trading and exchange on Osmosis. However, any attempt to route or trade the token now results in errors or restricted access, likely due to an unjustified block on routing.

Please review and correct the routing configuration to restore this token's functionality. It is also worth noting that the block appears to have occurred without an official DAO decision, so addressing this issue would support DAO governance principles for the community.

**Comment by p0mvn** [comment]
It works ser - we do not blacklist anything 😅 

```
curl "https://sqsprod.osmosis.zone/router/quote?tokenIn=200uosmo&tokenOutDenom=ibc%2F4925733868E7999F5822C961ADE9470A7FC5FA4A560BAE1DE102783C3F64C201&humanDenoms=false"

{
  "amount_in": {
    "denom": "uosmo",
    "amount": "200"
  },
  "amount_out": "388856",
  "route": [
    {
      "pools": [
        {
          "id": 1449,
          "type": 2,
          "balances": [],
          "spread_factor": "0.002000000000000000",
          "token_out_denom": "ibc/9A76CDF0CBCEF37923F32518FA15E5DC92B9F56128292BC4D63C4AEA76CBB110",
          "taker_fee": "0.002000000000000000"
        },
        {
          "id": 2218,
          "type": 2,
          "balances": [],
          "spread_factor": "0.000100000000000000",
          "token_out_denom": "ibc/4925733868E7999F5822C961ADE9470A7FC5FA4A560BAE1DE102783C3F64C201",
          "taker_fee": "0.001000000000000000"
        }
      ],
      "has-cw-pool": false,
      "out_amount": "388856",
      "in_amount": "200"
    }
  ],
  "effective_fee": "0.002998000000000000",
  "price_impact": "-0.002100362594405285",
  "in_base_out_quote_spot_price": "1960.123227093697952790"
}
```

**Comment by raphaellafar** [comment]
![obraz](https://github.com/user-attachments/assets/c1a1f0f9-b810-44aa-8d8e-e1ba0604655a)
https://github.com/osmosis-labs/sqs/blob/cdeb3af473102930ebf34540331a9cb95ce57ed5/tests/conftest.py#L149

**Comment by p0mvn** [comment]
That's a test

**Comment by raphaellafar** [comment]
I know, but as you can see the token is assigned to "token_blacklist".

**Comment by raphaellafar** [comment]
osmosisd query gamm pools --limit 3000 --output json | jq | grep id
![obraz](https://github.com/user-attachments/assets/ada8dc9b-c132-45c9-985d-4a622fa0b8e9)
no pools 2217 and 2218
